# Generated by Django 4.2.4 on 2023-09-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studenti', '0001_initial'),
        ('Appunti', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recenzione',
            old_name='appunto',
            new_name='appunto_recenzionato',
        ),
        migrations.RenameField(
            model_name='recenzione',
            old_name='Testo_recenzione',
            new_name='testo_recenzione',
        ),
        migrations.AlterField(
            model_name='appunto',
            name='voto_medio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='recenzione',
            unique_together={('studente', 'appunto_recenzionato', 'data_recenzione')},
        ),
    ]
