# Generated by Django 4.2.4 on 2023-09-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Studenti', '0001_initial'),
        ('Appunti', '0002_rename_appunto_recenzione_appunto_recenzionato_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scarica',
            old_name='appunto',
            new_name='appunto_scaricato',
        ),
        migrations.AlterUniqueTogether(
            name='scarica',
            unique_together={('studente', 'appunto_scaricato')},
        ),
    ]
