# Generated by Django 4.2.4 on 2023-09-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appunti', '0003_rename_appunto_scarica_appunto_scaricato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appunto',
            name='voto_medio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
