# Generated by Django 4.2.4 on 2023-09-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appunti', '0004_alter_appunto_voto_medio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentoPDF',
        ),
        migrations.AddField(
            model_name='appunto',
            name='nome_appunto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appunto',
            name='pdf_appunto',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
