# Generated by Django 4.2.4 on 2023-09-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appunti', '0005_delete_documentopdf_appunto_nome_appunto_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appunto',
            unique_together={('nome_appunto', 'pdf_appunto')},
        ),
    ]
