# Generated by Django 4.2.4 on 2023-09-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appunti', '0006_alter_appunto_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scarica',
            name='voto_assegnato',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
