# Generated by Django 4.2.4 on 2023-09-04 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Studenti', '0001_initial'),
        ('Appunti', '0007_alter_scarica_voto_assegnato'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scarica',
            unique_together={('studente', 'appunto_scaricato', 'data_scaricamento')},
        ),
    ]
